image: node:12

pipelines:
  default:
    - step:
        caches:
          - node
          - yarn
        script:
          - yarn install --prefer-offline
          - yarn validate

  branches:
    develop:
      - step:
          name: Deploy to Develop
          caches:
            - node
            - yarn
          deployment: Test
          script:
            - yarn install --prefer-offline
            - yarn validate
            - yarn deploy develop

    staging:
      - step:
          name: Deploy to Staging
          caches:
            - node
            - yarn
          deployment: Staging
          script:
            - yarn install --prefer-offline
            - yarn validate
            - yarn deploy staging

    master:
      - step:
          name: Deploy to Production
          caches:
            - node
            - yarn
          deployment: Production
          script:
            - yarn install --prefer-offline
            - yarn validate
            - yarn deploy production

definitions:
  caches:
    yarn: /usr/local/share/.cache/yarn
